name: DevSecOps Pipeline

on:
  push:
    branches:
      - main
      - develop

  pull_request:
    branches:
      - main


jobs:
  Import_SQL:
    runs-on: ubuntu-latest
    name: MySQL Deploy Action
    needs: [sonarcloud,dependency_check]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: gtadam/mysql-deploy-action@v1
        with:
            DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
            DATABASE_PORT: ${{ secrets.DATABASE_PORT }}
            DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
            DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
            DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
            DATABASE_SCRIPT: ${{ secrets.DATABASE_SCRIPT }}

  Deploy_staging:
    name: Deploy Staging
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    environment: 
      name: staging
      url: https://
    needs: [Import_SQL]
    steps:
      - uses: actions/checkout@v2
      - name: Upload ftp
        uses: sebastianpopp/ftp-action@releases/v2
        with:
          host: ${{ secrets.FTP_SERVER }}
          user: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          localDir: "."
          remoteDir: "gastonbarbaccia/" 